name: Site personnel de Sergei

# remote_theme: hydecorp/hydejack@v9.1.6
# remote_theme: pages-themes/leap-day@v0.2.0
# remote-theme: jekyll-theme-feeling-responsive@1.1
  remote_theme: chrisrhymes/bulma-clean-theme
# remote_theme: pages-themes/merlot@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-menus
# - jekyll-include-cache

description: Essais en Markdown + Jekyll !
