name: Site personnel de Sergei

# remote_theme: hydecorp/hydejack@v9.1.6
# remote_theme: pages-themes/leap-day@v0.2.0
# remote-theme: jekyll-theme-feeling-responsive@1.1
# remote_theme: aksakalli/jekyll-doc-theme@gh-pages NON
# remote_theme: rundocs/jekyll-rtd-theme non
# remote_theme: pages-themes/merlot@v0.2.0
remote_theme: just-the-docs/just-the-docs@v0.7.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-menus
# - jekyll-include-cache

---
layout: default
title: Customization
nav_order: 4
---

description: Essais en Markdown + Jekyll !
