title: Woodworking Hobby

# search_enabled: true

# Set a path/url to a logo that will be displayed instead of the title
# logo: "/media/lignarius_Small_1.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/media/Lignarius.ico"

description: Markdown + Jekyll + "Just the Docs" jekyll theme + GitHub Pages

baseurl: ""
url: "https://https://garlatti.github.io"

remote_theme: just-the-docs/just-the-docs@v0.7.0

plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-menus
  - jekyll-multiple-languages-plugin
#  - octopress-multilingual
# - jekyll-include-cache

languages: ["en", "fr"]


