name: Site personnel de Sergei
# theme: jekyll-theme-hydejack
remote_theme: hydecorp/hydejack@v9.1.6
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-include-cache
description: regarder mes essais en MD updates!
