remote_theme: just-the-docs/just-the-docs@v0.7.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-menus
# - jekyll-include-cache


title: The new handyman

search_enabled: false

# Set a path/url to a logo that will be displayed instead of the title
logo: "/media/lignarius.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/media/Lignarius.ico"

description: Markdown + Jekyll + "Just the Docs" jekyll theme + GitHub Pages
