title: The new handyman

name: Site personnel de Sergei

# remote_theme: hydecorp/hydejack@v9.1.6
# remote_theme: pages-themes/leap-day@v0.2.0
# remote-theme: jekyll-theme-feeling-responsive@1.1
# remote_theme: aksakalli/jekyll-doc-theme@gh-pages NON
# remote_theme: rundocs/jekyll-rtd-theme non
# remote_theme: pages-themes/merlot@v0.2.0
remote_theme: just-the-docs/just-the-docs@v0.7.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-menus
# - jekyll-include-cache

# Color scheme supports "light" (default) and "dark"
# color_scheme: dark

search_enabled: false

# Set a path/url to a logo that will be displayed instead of the title
logo: "/media/lignarius.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/media/Lignarius.ico"

description: Markdown + Jekyll + "Just the Docs" jekyll theme + GitHub Pages
